
import Header from "@/components/Header";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "aBit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <div className=" bg-cover bg-center">
            <div className=" relative z-20">
              <Header/>
            </div>
            
          </div>
          <div className="">
          {children}
          </div>
      </body>
    </html>
  );
}
