
import Header from "@/components/Header";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import Image from "next/image";
import coverimage  from '/assets/coverimage.png'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <div className=" bg-cover bg-center">
            <Image src={coverimage} alt='cover image' className=" absolute z-10 w-screen h-fit"/>
            <div className=" relative z-20">
              <Header/>
            </div>
          </div>
          <div className=" relative bg-green-300">
          {children}
          </div>
      </body>
    </html>
  );
}
